// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7UgbSdUXcPdMnVQoYSNniKs8VvxDiw0s',
    appId: '1:1005150037788:web:960791936b3aaaf2f57cd9',
    messagingSenderId: '1005150037788',
    projectId: 'maps-api-for-pa-pens',
    authDomain: 'maps-api-for-pa-pens.firebaseapp.com',
    storageBucket: 'maps-api-for-pa-pens.appspot.com',
    measurementId: 'G-9K0RMY9Y97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwSrMemsGhDmzbYuHxKNN-i4LmJ-jxko',
    appId: '1:1005150037788:android:92737cf5ae1efb00f57cd9',
    messagingSenderId: '1005150037788',
    projectId: 'maps-api-for-pa-pens',
    storageBucket: 'maps-api-for-pa-pens.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmudStm4AGh4NM6JRdLOO5BH_CUDumewE',
    appId: '1:1005150037788:ios:f20a7ae1b15a780ef57cd9',
    messagingSenderId: '1005150037788',
    projectId: 'maps-api-for-pa-pens',
    storageBucket: 'maps-api-for-pa-pens.appspot.com',
    iosBundleId: 'com.example.travelguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmudStm4AGh4NM6JRdLOO5BH_CUDumewE',
    appId: '1:1005150037788:ios:f20a7ae1b15a780ef57cd9',
    messagingSenderId: '1005150037788',
    projectId: 'maps-api-for-pa-pens',
    storageBucket: 'maps-api-for-pa-pens.appspot.com',
    iosBundleId: 'com.example.travelguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7UgbSdUXcPdMnVQoYSNniKs8VvxDiw0s',
    appId: '1:1005150037788:web:8786b4c50b98dcebf57cd9',
    messagingSenderId: '1005150037788',
    projectId: 'maps-api-for-pa-pens',
    authDomain: 'maps-api-for-pa-pens.firebaseapp.com',
    storageBucket: 'maps-api-for-pa-pens.appspot.com',
    measurementId: 'G-S7MJ5BSCZF',
  );
}
